services:
  wordpress:
    container_name: wordpress
    ports:
      - "8080:80"
    build: requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    env_file: .env

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      device: ${HOME}/data/mariadb
      o : bind
      type : none
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      device: ${HOME}/data/wordpress
      o : bind
      type : none
