version: '3.8'

services:
  wordpress:
    container_name: wordpress
    build: requirements/wp-fpm
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "8080:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    # env_file: .env 

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      device: ${HOME}/data/mariadb
      o : bind
      type : none
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      device: ${HOME}/data/wordpress
      o : bind
      type : none
